store/products/urls.py
from django.urls import path
from products.views import products, basket_add, basket_delete

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('<int:category_id>/', products, name='category'),
    path('page/<int:page>/', products, name='page'),
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-delete/<int:id>/', basket_delete, name='basket_delete')

]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from products.views import index, products


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/users/urls.py
from django.urls import path
from users.views import login, register, profile, logout

app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout')
]

store/products/models.py
from django.db import models

from users.models import User

# Create your models here.

class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'Product Categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.00)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE) # Если удалится категория
    # удалится и все продукты связанные с категорией
    # можно использовать PROTECT вместо CASCADE чтобы изменить ситуация так что категорию невозможно было бы удалить
    # пока есть продукты связанные с категорией

    def __str__(self):
        return f'{self.name} | {self.category.name}'

class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

store/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from products.models import ProductCategory, Product, Basket
from django.contrib.auth.decorators import login_required

from django.core.paginator import Paginator
# Create your views here.

def index(request):

    context = {
        'title':'Store'
    }
    return render(request, 'products/index.html', context)

def products(request, category_id=None, page=1):
    context = {'title': 'Store - Каталог', 'categories': ProductCategory.objects.all()}
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    paginator = Paginator(products, 3)
    products_paginator = paginator.page(page)
    context.update({'products': products_paginator})
    return render(request, 'products/products.html', context)


@login_required
def basket_add(request, product_id):
    current_page = request.META.get('HTTP_REFERER')
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
        return HttpResponseRedirect(current_page)
    else:
        basket = baskets.first()
        basket.quantity += 1
        basket.save()
        return HttpResponseRedirect(current_page)


@login_required
def basket_delete(request, id):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


























# def test_context(request):
#     context = {
#         'title':'store',
#         'header':'Добро пожаловать',
#         'username':'Иван Иванов',
#         'products': [
#             {'name':'Худи черного цвета с монограммами adidas Originals', 'price':6090.00},
#             {'name': 'Синяя куртка The North Face', 'price': 23725.00},
#             {'name': 'Коричневый спортивный oversized-топ ASOS DESIGN', 'price': 3390.00},
#             {'name': 'Черный рюкзак Nike Heritage', 'price': 2340.00},
#         ],
#         'products_of_promotions':[
#             {'name': 'Черные туфли на платформе с 3 парами люверсов Dr Martens 1461 Bex', 'old_price': 13590.00, 'discount': 10590.00},
#             {'name': 'Темно-синие широкие строгие брюки ASOS DESIGN', 'old_price': 2890.00, 'discount': 1890.00},
#         ]
#     }
#     return render(request, 'products/test-context.html', context)

store/products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title|title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index'%}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index'%}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile'%}">Профиль
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    {% if user.is_superuser or user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index'%}" target="_blank">Админ-панель
                                <i class="fas fa-user-circle"></i>
                            </a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout'%}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% else %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login'%}">Войти <i class="fas fa-sign-in-alt"></i></a>
                     </li>
                {% endif %}



            </ul>
        </div>
    </div>
</nav>

{% block content %} {% endblock %}

{% block footer %} {% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js'%}" crossorigin="anonymous"></script>

</body>

</html>

store/products/templates/products/basket.html
{% if baskets %}
     <div class="col-lg-5">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
            </h4>
         {% for basket in baskets %}
             <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ basket.product.name }}</h5>
                    <p class="card-text">{{ basket.product.short_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                        <span class="text-muted">{{ basket.quantity }}</span>
                        <span class="text-muted">{{ basket.sum }} руб.</span>
                        <span class="text-muted">
                            <a href="{% url 'products:basket_add' basket.product.id %}" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-plus"></i>
                            </a>
                            <a href="{% url 'products:basket_delete' basket.id %}" style="text-decoration: none; color: gray;">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
         {% endfor %}

            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">{{ total_sum }} руб.</h4>
                </div>
            </div>
            <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
        </div>
{% else %}
    <div class="col-lg-5">
            <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
                Корзина пуста <span class="badge badge-secondary badge-pill">{{ total_quantity }}</span>
            </h4>

             <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Название продукта</h5>
                    <p class="card-text">В данную корзину будет добавлятся продукты</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between lh-condensed bg-light">
                        <span class="text-muted">количество</span>
                        <span class="text-muted">цена руб.</span>
                        <span class="text-muted">
                            <a href="#" style="text-decoration: none; color: gray;">
                                <i class="fas fa-cart-plus"></i>
                            </a>
                            <a href="#" style="text-decoration: none; color: gray;">
                                <i class="far fa-trash-alt"></i>
                            </a>
                        </span>
                    </li>
                </ul>
            </div>


            <div class="card mb-3">
                <div class="card-footer">
                    <p class="float-left">Итого</p>
                    <h4 class="float-right">{{ total_sum }} руб.</h4>
                </div>
            </div>
            <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
        </div>
{% endif %}

store/products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}
{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index'%}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}





























<!--{% load static %}-->
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->

<!--<head>-->

<!--    <meta charset="utf-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">-->
<!--    <meta name="description" content="">-->
<!--    <meta name="author" content="">-->

<!--    <title>Store</title>-->

<!--    &lt;!&ndash; Bootstrap core CSS &ndash;&gt;-->
<!--    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">-->

<!--    &lt;!&ndash; Custom styles for this template &ndash;&gt;-->
<!--    <link href="{% static 'css/index.css' %}" rel="stylesheet">-->

<!--</head>-->

<!--<body>-->

<!--&lt;!&ndash; Navigation &ndash;&gt;-->
<!--<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">-->
<!--    <div class="container">-->
<!--        <a class="navbar-brand" href="{% url 'index'%}">Store</a>-->
<!--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"-->
<!--                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--        </button>-->
<!--        <div class="collapse navbar-collapse" id="navbarResponsive">-->
<!--            <ul class="navbar-nav ml-auto">-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="{% url 'products'%}">Каталог <i class="fas fa-shopping-bag"></i> </a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="auth/login.html">Войти <i class="fas fa-sign-in-alt"></i></a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="auth/profile.html">Валерий П.-->
<!--                        <i class="fas fa-user-circle"></i>-->
<!--                    </a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Выйти <i class="fas fa-sign-out-alt"></i></a>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->
<!--    </div>-->
<!--</nav>-->

<!--&lt;!&ndash;&lt;!&ndash; Page Content &ndash;&gt;&ndash;&gt;-->
<!--&lt;!&ndash;<section>&ndash;&gt;-->
<!--&lt;!&ndash;    <div class="container">&ndash;&gt;-->
<!--&lt;!&ndash;        <div class="row">&ndash;&gt;-->
<!--&lt;!&ndash;            <div class="col-lg-6">&ndash;&gt;-->
<!--&lt;!&ndash;                <h1 class="mt-5">Store</h1>&ndash;&gt;-->
<!--&lt;!&ndash;                <p>&ndash;&gt;-->
<!--&lt;!&ndash;                    Новые образы и лучшие бренды Store.&ndash;&gt;-->
<!--&lt;!&ndash;                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.&ndash;&gt;-->
<!--&lt;!&ndash;                </p>&ndash;&gt;-->
<!--&lt;!&ndash;                <button id="start-purchase-btn" type="button" class="btn btn-lg">&ndash;&gt;-->
<!--&lt;!&ndash;                    <a id="start-purchase-link" href="{% url 'products'%}">&ndash;&gt;-->
<!--&lt;!&ndash;                        Начать покупки&ndash;&gt;-->
<!--&lt;!&ndash;                    </a>&ndash;&gt;-->
<!--&lt;!&ndash;                </button>&ndash;&gt;-->
<!--&lt;!&ndash;            </div>&ndash;&gt;-->
<!--&lt;!&ndash;        </div>&ndash;&gt;-->
<!--&lt;!&ndash;    </div>&ndash;&gt;-->
<!--&lt;!&ndash;</section>&ndash;&gt;-->

<!--&lt;!&ndash; Bootstrap core JavaScript &ndash;&gt;-->
<!--<script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>-->
<!--<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>-->

<!--&lt;!&ndash; FontAwesome script &ndash;&gt;-->
<!--<script src="{% static 'vendor/fontawesome/fontawesome-icons.js'%}" crossorigin="anonymous"></script>-->

<!--</body>-->

<!--</html>-->

store/products/templates/products/test-context.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title|title }}</title>   <!--| - прикрепление функции в нашем случаи каждое слово начинается с большой буквы-->
</head>
<body>
<h1>{{ header }}</h1>
<p>{{ username }}</p>
<table border="1">
    <tr>
        <th>Name product</th>
        <th colspan="2">Price</th>
    </tr>
{% for product in products %} <!--Создаем цикл чтобы вывести весь словарь по одному-->
    <tr>
        <td>{{ product.name }}</td>
        <td align="center" colspan="2">{{ product.price }}.руб</td>
    </tr>
{% endfor %}

{% if products_of_promotions %} <!--Создаем условие если список пустой ничего не выводит если что то есть выводит-->
    <tr>
        <th style="background:red; color:white">Акция</th>
        <th style="background:red; color:white">Старая цена</th>
        <th style="background:red; color:white">Акция</th>
    </tr>
    {% for product in products_of_promotions %}
        <tr>
            <td>{{ product.name }}</td>
            <td align="center"><s>{{ product.old_price }}.руб</s></td>
            <td align="center">{{ product.discount }}.руб</td>
        </tr>
    {% endfor %}
{% endif %}
</table>
</body>
</html>